### ISSUE TITLE
failed wb_get_size()

### ISSUE THREAD

**Issue by ghostjat** [wagy/WinBinder#7]
Try to get the window dimension on Resize using 
wb_get_size($wind);
but nothing is returning
would you please help in this?

**Comment by wagy** [comment]
Yes there was a problen since migrate to php 7.
Now it works:
wb_get_size(0);                                                      => null
wb_get_size(123);                                                  => null
wb_get_size($window);                                          =>[xsize,ysize]
$img = wb_load_image(PATH_RES . "ttf.ico");
wb_get_size($img, true);                                        =>[image_x, image_y]
wb_get_size($listView_ctrl, $lparam2);                   =>[colsize_1,colsize_2...]

[php_winbinder.zip](https://github.com/wagy/WinBinder/files/2568330/php_winbinder.zip)
